blueprint:
  name: Button Toggle
  domain: automation
  input:
    button_device_id:
      name: Button
      selector:
        device:
          filter:
            - integration: mqtt
              model: Smart button
            - integration: mqtt
              model: Wireless switch with 1 button
    switch_entity_ids:
      name: Switch
      selector:
        entity:
          filter:
            - domain: switch
          multiple: true
    triggers:
      name: Triggers
      selector:
        select:
          options:
            - button_double_press
            - button_hold_press
            - button_single_press
          multiple: true

triggers:
  - domain: mqtt
    device_id: !input button_device_id
    type: action
    id: button_double_press
    subtype: double
    trigger: device
  - domain: mqtt
    device_id: !input button_device_id
    type: action
    id: button_hold_press
    subtype: hold
    trigger: device
  - domain: mqtt
    device_id: !input button_device_id
    type: action
    id: button_single_press
    subtype: single
    trigger: device
actions:
  - repeat:
      for_each: !input switch_entity_ids
      sequence:
        - variables:
            switch_entity: "{{ repeat.item }}"
            trigger_id: "{{ trigger.id }}"
            button_single_press: "{{ trigger_id == 'button_single_press' and 'button_single_press' in !input triggers }}"
            button_double_press: "{{ trigger_id == 'button_double_press' and 'button_double_press' in !input triggers }}"
            button_hold_press: "{{ trigger_id == 'button_hold_press' and 'button_hold_press' in !input triggers }}"
        - if:
            - condition: template
              value_template: "{{ button_single_press or button_double_press or button_hold_press }}"
          then:
            - service: switch.toggle
              target:
                entity_id: "{{ switch_entity }}"
              data: {}
mode: single
