blueprint:
  name: Button Toggle
  domain: automation
  input:
    button_device_id:
      name: Button
      selector:
        device:
          filter:
            - integration: mqtt
              model: Smart button
            - integration: mqtt
              model: Wireless switch with 1 button
    switch_entity_ids:
      name: Switch
      selector:
        entity:
          filter:
            - domain: switch
          multiple: true
    triggers:
      name: Triggers
      selector:
        select:
          mode: dropdown 
          options:
            - "single"
            - "hold"
            - "double"
            - "1_single"
            - "1_hold"
            - "1_double"
            - "2_single"
            - "2_hold"
            - "2_double"
            - "3_single"
            - "3_hold"
            - "3_double"
            - "4_single"
            - "4_hold"
            - "4_double"  
          multiple: true
triggers:
  - domain: mqtt
    device_id: !input button_device_id
    type: action
    id: button_double_press
    subtype: double
    trigger: device
  - domain: mqtt
    device_id: !input button_device_id
    type: action
    id: button_hold_press
    subtype: hold
    trigger: device
  - domain: mqtt
    device_id: !input button_device_id
    type: action
    id: button_single_press
    subtype: single
    trigger: device
actions:
  - repeat:
      for_each: !input switch_entity_ids
      sequence:
        - variables:
            switch_entity: "{{ repeat.item }}"
            trigger_id: "{{ trigger.id }}"
            input_triggers: !input triggers
            button_single_press: "{{ trigger_id == 'button_single_press' and 'button_single_press' in input_triggers }}"
            button_double_press: "{{ trigger_id == 'button_double_press' and 'button_double_press' in input_triggers }}"
            button_hold_press: "{{ trigger_id == 'button_hold_press' and 'button_hold_press' in input_triggers }}"
        - if:
            - condition: template
              value_template: "{{ button_single_press or button_double_press or button_hold_press }}"
          then:
            - service: switch.toggle
              target:
                entity_id: "{{ switch_entity }}"
              data: {}
mode: single
