blueprint:
  name: Curtain
  domain: automation
  input:
    button_device_id:
      name: Button
      selector:
        device:
          filter:
            - integration: mqtt
              model: Smart button
            - integration: mqtt
              model: Wireless switch with 1 button
            - integration: mqtt
              model: Star Ring 4 Gang Scene Switch
    button_number:
      name: Button Number
      description: Has no effect when its a single button
      selector:
        select:
          mode: dropdown 
          options:
            - label: "1"
              value: "1"
            - label: "2"
              value: "2"
            - label: "3"
              value: "3"
            - label: "4"
              value: "4"
    curtain_entity_ids:
      name: Curtain
      selector:
        entity:
          filter:
            - domain: cover
          multiple: true

triggers:
  - domain: mqtt
    device_id: !input button_device_id
    type: action
    id: button_double_press
    subtype: double
    trigger: device
  - domain: mqtt
    device_id: !input button_device_id
    type: action
    id: button_double_press
    subtype: "{{ !input button_number }}_double"
    trigger: device
  - domain: mqtt
    device_id: !input button_device_id
    type: action
    id: button_hold_press
    subtype: hold
    trigger: device
  - domain: mqtt
    device_id: !input button_device_id
    type: action
    id: button_hold_press
    subtype: "{{ !input button_number }}_hold"
    trigger: device
actions:
  - repeat:
      for_each: !input curtain_entity_ids
      sequence:
        - variables:
            curtain_entity: "{{ repeat.item }}"
            trigger_id: "{{ trigger.id }}"
            curtain_state: "{{ states(curtain_entity) }}"
            curtain_open: "{{ is_state(curtain_entity, 'open') }}"
            button_double_press: "{{ trigger_id == 'button_double_press' }}"
            button_hold_press: "{{ trigger_id == 'button_hold_press' }}"
        - if: 
          - condition: template
            value_template: "{{ curtain_open and button_double_press }}"
          then:
            - service: cover.close_cover
              target:
                entity_id: "{{ curtain_entity }}"
              data: {}
        - if:
          - condition: template
            value_template: "{{ (not curtain_open) and button_double_press }}"
          then:
            - service: cover.open_cover
              target:
                entity_id: "{{ curtain_entity }}"
              data: {}
        - if: 
          - condition: template
            value_template: "{{ button_hold_press }}"
          then:
            - service: cover.stop_cover
              target:
                entity_id: "{{ curtain_entity }}"
              data: {}
mode: single
