blueprint:
  name: Curtain
  domain: automation
  input:
    button_device_id:
      name: Button
      selector:
        device:
          filter:
            - integration: mqtt
              model: Smart button
            - integration: mqtt
              model: Wireless switch with 1 button
            - integration: mqtt
              model: Star Ring 4 Gang Scene Switch
    toggle_trigger:
      name: Toggle trigger
      selector:
        select:
          mode: dropdown 
          options:
            - "single"
            - "hold"
            - "double"
            - "1_single"
            - "1_hold"
            - "1_double"
            - "2_single"
            - "2_hold"
            - "2_double"
            - "3_single"
            - "3_hold"
            - "3_double"
            - "4_single"
            - "4_hold"
            - "4_double"    
    hold_trigger:
      name: Hold trigger
      selector:
        select:
          mode: dropdown 
          options:
            - "single"
            - "hold"
            - "double"
            - "1_single"
            - "1_hold"
            - "1_double"
            - "2_single"
            - "2_hold"
            - "2_double"
            - "3_single"
            - "3_hold"
            - "3_double"
            - "4_single"
            - "4_hold"
            - "4_double" 
    curtain_entity_ids:
      name: Curtain
      selector:
        entity:
          filter:
            - domain: cover
          multiple: true

triggers:
  - domain: mqtt
    device_id: !input button_device_id
    type: action
    id: toggle_press
    subtype: !input toggle_trigger
    trigger: device
  - domain: mqtt
    device_id: !input button_device_id
    type: action
    id: hold_press
    subtype: !input hold_trigger
    trigger: !input button_device_id
actions:
  - repeat:
      for_each: !input curtain_entity_ids
      sequence:
        - variables:
            curtain_entity: "{{ repeat.item }}"
            trigger_id: "{{ trigger.id }}"
            curtain_state: "{{ states(curtain_entity) }}"
            curtain_open: "{{ is_state(curtain_entity, 'open') }}"
            button_double_press: "{{ trigger_id == 'toggle_press' }}"
            button_hold_press: "{{ trigger_id == 'hold_press' }}"
        - if: 
          - condition: template
            value_template: "{{ curtain_open and toggle_press }}"
          then:
            - service: cover.close_cover
              target:
                entity_id: "{{ curtain_entity }}"
              data: {}
        - if:
          - condition: template
            value_template: "{{ (not curtain_open) and toggle_press }}"
          then:
            - service: cover.open_cover
              target:
                entity_id: "{{ curtain_entity }}"
              data: {}
        - if: 
          - condition: template
            value_template: "{{ hold_press }}"
          then:
            - service: cover.stop_cover
              target:
                entity_id: "{{ curtain_entity }}"
              data: {}
mode: single
