blueprint:
  name: Light
  domain: automation
  input:
    button_device_id:
      name: Button
      selector:
        device:
          filter:
            - integration: mqtt
              model: Smart button
            - integration: mqtt
              model: Wireless switch with 1 button
            - integration: mqtt
              model: Smart knob
    light_entity_ids:
      name: Light
      selector:
        entity:
          filter:
            - domain: light
          multiple: true
    trigger:
      name: Trigger
      selector:
        select:
          mode: dropdown 
          options:
            - "single"
            - "hold"
            - "double"
            - "1_single"
            - "1_hold"
            - "1_double"
            - "2_single"
            - "2_hold"
            - "2_double"
            - "3_single"
            - "3_hold"
            - "3_double"
            - "4_single"
            - "4_hold"
            - "4_double" 
triggers:
  - domain: mqtt
    device_id: !input button_device_id
    type: action
    id: button
    subtype: !input trigger
    trigger: device
  - domain: mqtt
    device_id: !input button_device_id
    type: action
    id:  left
    subtype: rotate_left
    trigger: device
  - domain: mqtt
    device_id: !input button_device_id
    type: action
    id:  right
    subtype: rotate_right
    trigger: device
actions:
  - repeat:
      for_each: !input light_entity_ids
      sequence:
        - variables:
            light_entity: "{{ repeat.item }}"
            trigger_id: "{{ trigger.id }}"
            input_triggers: !input triggers
            button: "{{ trigger_id == 'button'  }}"
            right: "{{ trigger_id == 'right' }}"
            left: "{{ trigger_id == 'left' }}"
        - if:
            - condition: template
              value_template: "{{ button }}"
          then:
            - service: light.toggle
              target:
                entity_id: "{{ light_entity }}"
              data: {}
        - if:
            - condition: template
              value_template: "{{ right }}"
          then:
            - service: light.turn_on
              target:
                entity_id: "{{ light_entity }}"
              data:
                brightness_step: 5
        - if:
            - condition: template
              value_template: "{{ left }}"
          then:
            - service: light.turn_on
              target:
                entity_id: "{{ light_entity }}"
              data:
                brightness_step: -5
    
mode: single
